INSERT INTO MEMBER(ID, NAME, AGE, EMAIL) VALUES('env', 'DEVELOPMENT', 1, 'DEVELOPMENT@DEVELOPMENT.COM');
INSERT INTO MEMBER(ID, NAME, AGE, EMAIL) VALUES('TEST1', 'TEST1', 1, 'TEST1@TEST.COM');
INSERT INTO MEMBER(ID, NAME, AGE, EMAIL) VALUES('TEST2', 'TEST2', 2, 'TEST2@TEST.COM');
INSERT INTO MEMBER(ID, NAME, AGE, EMAIL) VALUES('TEST3', 'TEST3', 3, 'TEST3@TEST.COM');
INSERT INTO MEMBER(ID, NAME, AGE, EMAIL) VALUES('TEST4', 'TEST4', 4, 'TEST4@TEST.COM');
INSERT INTO MEMBER(ID, NAME, AGE, EMAIL) VALUES('TEST5', 'TEST5', 5, 'TEST5@TEST.COM');
INSERT INTO MEMBER(ID, NAME, AGE, EMAIL) VALUES('TEST6', 'TEST6', 6, 'TEST6@TEST.COM');